- name: Install jetty9 webserver
  hosts: localhost
  tasks:
     - name: Update apt before installing the Jetty9 webserver
       apt:
         upgrade: yes
         update_cache: true
         cache_valid_time: 3600
         force_apt_get: true
       ignore_errors: yes

     - name: installing the jetty9 webserver
       apt:
         name: jetty9
         state: latest

     - name: start jetty9
       service:
         name: jetty9
         state: started

     - name: To check and verify jetty9 webserver is running
       command: service jetty9 status
       register: result
    
     - name: Print output of result file
       debug:
         msg: "{{ result.stdout_lines }}" 
